package com.example.Ultracar.enums;

public enum Situation {
    PENDENTE,
    REPARAR,
    EM_PROGRESSO,
    COMPLETO,
    DIAGNOSTICO_NECESSARIO,
    REJEITADO,
    AGUARDANDO_APROVACAO,
    CANCELADO,
    ENTREGA_AGENDADA,
    AGENDADO_PARA_REPARO
}
